
export let ControllerTemplate :string = `
// OVERCAST engine created by Michael Roberts
// THIS IS AUTOGENERATED CODE DO NOT MAKE CHANGES

import * as mssql from "mssql";
import { createQuery ,createFilter } from "odata-v4-mssql";
import { ODataController, Edm, odata, ODataQuery } from "odata-v4-server";
import {Overcast  } from "overcast";
import {config} from "../../config";
{{#dependencies}}
import { {{dependency}} } from "../../Models/{{dependency}}/{{dependency}}";

{{/dependencies}}

export class {{entityName}}ControllerAutoGen extends ODataController {
    
  {{&findOne}}
  {{&find}}
  {{&post}}
  {{&patch}}
  {{&delete}}
  {{&put}}
  {{#methods}}
  {method}
  {{/methods}}

} `;
